using Domain.Abstractions.Entitys;
using Domain.Abstractions.Entitys.AnalisysConfig;
using Domain.Abstractions.Enums;
using Domain.Abstractions.Services;
using System;
using System.Collections.Generic;
using System.Text;

namespace Domain.Abstractions.Services
{
	/// <summary>
	/// Relative Strength Index (RSI) is a momentum oscillator that measures the speed and change of price movements. RSI oscillates between zero and 100. Traditionally, and according to Wilder, RSI is considered overbought when above 70 and oversold when below 30. Signals can also be generated by looking for divergences, failure swings, and centerline crossovers. RSI can also be used to identify the general trend.
	/// http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:relative_strength_index_rsi
	/// </summary>
	public interface IRSIAnaliser
	{
		/// <summary>
		/// Relative Strength Index
		/// </summary>
		decimal RSI { get; }
		/// <summary>
		/// RSI is considered overbought when above 70 and oversold when below 30
		/// </summary>
		PriceSignal PriceSignal { get; }
		/// <summary>
		/// RSI tends to fluctuate between 40 and 90 in a uptrend and between 10 and 60 in a downtrend with the 50-60 zone acting as neutral.
		/// </summary>
		Trend RSIRange { get; }
		/// <summary>
		/// A uptrend divergence occurs when the underlying security makes a lower low and RSI forms a higher low 
		/// A downtrend divergence forms when the security records a higher high and RSI forms a lower high.
		/// </summary>
		Trend Divergence { get; }
		/// <summary>
		/// A uptrend failure swing forms when RSI moves below 30 (oversold), bounces above 30, pulls back, holds above 30 and then breaks its prior high 
		/// A downtrend failure swing forms when RSI moves above 70, pulls back, bounces, fails to exceed 70 and then breaks its prior low.
		/// </summary>
		Trend FailSwing { get; }
		/// <summary>
		/// A positive reversal, genarate a uptrend forms when RSI forges a lower low and the security forms a higher low. This lower low is not at oversold levels, but somewhere between 30 and 50.
		/// A negative reversal, genarate a downtrend is the opposite of a positive reversal. RSI forms a higher high, but the security forms a lower high. Again, the higher high is usually just below overbought levels in the 50-70 area.
		/// </summary>
		Trend PositiveNegativeReversal { get; }
		IRSIAnaliser Calculate(IRSIConfig config, ICandleAnalyser analysis);
	}
}
